/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrApendice.java
 *
 * Created on 18-ene-2012, 18:09:23
 */
package interfaz;

import clases.Apendice;
import clases.Participante;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author jackpanzer
 */
public class jfrApendice extends javax.swing.JFrame {

    Interfaz padre;
    DefaultMutableTreeNode nodo;
    private boolean editar;
    /** Creates new form jfrApendice */
    public jfrApendice(Interfaz padre, DefaultMutableTreeNode nodo,boolean n_editar) {
        initComponents();
        this.nodo = nodo;
        this.padre = padre;
        for(int i=0;i<this.padre.getDoc().getPart_creados().size();i++)
        {
            this.jcmbAutor.addItem(this.padre.getDoc().getPart_creados().get(i));
        }
        this.editar=n_editar;
        if(n_editar)this.inicializar_edicion();
    }

    private void inicializar_edicion()
    {
        Apendice ap=(Apendice) this.nodo.getUserObject();
        this.jtxNombre.setText(ap.getNombre());
        this.jcmbAutor.setSelectedItem(ap.getAutor());
        if(ap.isTipo())
            this.jckApendice.setSelected(true);
        else
            this.jckSeccion.setSelected(true);
        this.jtxaComentario.setText(ap.getComentario());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcmbAutor = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jckSeccion = new javax.swing.JCheckBox();
        jckApendice = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaComentario = new javax.swing.JTextArea();
        jbtCancelar = new javax.swing.JButton();
        jbtAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir nueva seccion/apéndice");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jtxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxNombreKeyReleased(evt);
            }
        });

        jLabel2.setText("Autor:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        jckSeccion.setText("Sección");
        jckSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckSeccionActionPerformed(evt);
            }
        });

        jckApendice.setText("Apéndice");
        jckApendice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckApendiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jckSeccion)
                    .addComponent(jckApendice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jckSeccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jckApendice)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbAutor, 0, 363, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("General", jPanel1);

        jtxaComentario.setColumns(20);
        jtxaComentario.setLineWrap(true);
        jtxaComentario.setRows(5);
        jScrollPane1.setViewportView(jtxaComentario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Comentarios", jPanel2);

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtAceptar.setText("Aceptar");
        jbtAceptar.setEnabled(false);
        jbtAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancelar)
                    .addComponent(jbtAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(padre != null)
        {
            padre.setEnabled(true);
        }
        
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        // TODO add your handling code here:
        if(padre != null)
        {
            padre.setEnabled(true);
        }
        
        this.dispose();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jckSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckSeccionActionPerformed
        // TODO add your handling code here:
        jckSeccion.setSelected(true);
        jckApendice.setSelected(false);
        
        if(jtxNombre.getText().equals(""))
        {
            jbtAceptar.setEnabled(false);
        }
        else
        {
            jbtAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_jckSeccionActionPerformed

    private void jtxNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNombreKeyReleased
        // TODO add your handling code here:
        if(jtxNombre.getText().equals(""))
        {
            jbtAceptar.setEnabled(false);
        }
        else
        {
            if(jckApendice.isSelected() || jckSeccion.isSelected())
            {
                jbtAceptar.setEnabled(true);
            }
            else
            {
                jbtAceptar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jtxNombreKeyReleased

    private void jckApendiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckApendiceActionPerformed
        // TODO add your handling code here:
        jckSeccion.setSelected(false);
        jckApendice.setSelected(true);
        
        if(jtxNombre.getText().equals(""))
        {
            jbtAceptar.setEnabled(false);
        }
        else
        {
            jbtAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_jckApendiceActionPerformed

private void jbtAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAceptarActionPerformed
// TODO add your handling code here:
    if(nodo != null)
        {   //Apendice 
            if(!this.editar)
            {
                Apendice n_Apend = new Apendice();
                n_Apend.addObserver(this.padre);
                n_Apend.setNombre(this.jtxNombre.getText());
                n_Apend.setAutor((Participante)this.jcmbAutor.getSelectedItem());
                if(jckSeccion.isSelected()){
                    n_Apend.setTipo(false);
                }else if(jckApendice.isSelected()){
                    n_Apend.setTipo(true);
                }
                n_Apend.setComentario(this.jtxaComentario.getText());
                this.padre.getDoc().Crear_Apendice(n_Apend);
                DefaultMutableTreeNode child = new DefaultMutableTreeNode(n_Apend);
                nodo.add(child);
                this.padre.añadir_cosa(child);
                n_Apend.notificar_observer();
            }
            else
            {
                Apendice n_Apend=(Apendice)nodo.getUserObject();
                n_Apend.setNombre(this.jtxNombre.getText());
                n_Apend.setAutor((Participante)this.jcmbAutor.getSelectedItem());
                if(jckSeccion.isSelected()){
                    n_Apend.setTipo(false);
                }else if(jckApendice.isSelected()){
                    n_Apend.setTipo(true);
                }
                n_Apend.setComentario(this.jtxaComentario.getText());
                n_Apend.notificar_observer();
            }
            padre.setEnabled(true);
            this.dispose();
        }    
}//GEN-LAST:event_jbtAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrApendice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrApendice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrApendice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrApendice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new jfrApendice(null, null,false).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtAceptar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JCheckBox jckApendice;
    private javax.swing.JCheckBox jckSeccion;
    private javax.swing.JComboBox jcmbAutor;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextArea jtxaComentario;
    // End of variables declaration//GEN-END:variables
}
