/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrExcepcion.java
 *
 * Created on 26-nov-2011, 20:31:48
 */

package interfaz;

import clases.Caso_de_uso;
import clases.Evento;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Cervantes
 */
public class jfrExcepcion extends javax.swing.JFrame {

    private Interfaz Padre;
    private DefaultMutableTreeNode nodo_insertar;//nodo en el que insertar la excepcion
    private Caso_de_uso CU;
    private boolean editar;

    /** Creates new form jfrExcepcion */
    public jfrExcepcion(Interfaz auxPadre,DefaultMutableTreeNode auxnodo_insertar,
            Caso_de_uso auxCU,boolean n_editar)
    {
        initComponents();
        this.Padre=auxPadre;
        this.nodo_insertar=auxnodo_insertar;
        this.CU=auxCU;
        for(int i=0;i<this.CU.getPasos().size();i++)
            this.jcmbxNumPaso.addItem(this.CU.getPasos().get(i));
        this.editar=n_editar;
        if(n_editar)this.inicializar_edicion();
    }

    private void inicializar_edicion()
    {
        Evento ev=(Evento) this.nodo_insertar.getUserObject();
        this.jtxaDescripcion.setText(ev.getDescripcion());
        this.jcmbxNumPaso.setSelectedItem(ev.getNum_paso());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDescripcion = new javax.swing.JTextArea();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jcmbxNumPaso = new javax.swing.JComboBox();
        jlblNumPaso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir excepción...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Descripción: ");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtxaDescripcion.setColumns(20);
        jtxaDescripcion.setLineWrap(true);
        jtxaDescripcion.setRows(5);
        jtxaDescripcion.setName("jtxaDescripcion"); // NOI18N
        jScrollPane1.setViewportView(jtxaDescripcion);

        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.setName("jbtnAceptar"); // NOI18N
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setName("jbtnCancelar"); // NOI18N
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jcmbxNumPaso.setName("jcmbxNumPaso"); // NOI18N

        jlblNumPaso.setText("Número de paso");
        jlblNumPaso.setName("jlblNumPaso"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnCancelar)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(341, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblNumPaso)
                        .addGap(18, 18, 18)
                        .addComponent(jcmbxNumPaso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNumPaso)
                    .addComponent(jcmbxNumPaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAceptar)
                    .addComponent(jbtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        // TODO add your handling code here:
        if(!this.editar)
        {
            Evento ex=new Evento();
            ex.setNum_paso(this.jcmbxNumPaso.getSelectedIndex()+1);
            ex.setDescripcion(jtxaDescripcion.getText());
            ex.setTipo(true);
            ex.setPertenece(CU);
            ex.addObserver(this.Padre);
            this.CU.nuevaExcepcion(ex);
            this.nodo_insertar.add(new DefaultMutableTreeNode(ex));
            ex.notificar_observer();   
        }
        else
        {
            Evento ex=(Evento) this.nodo_insertar.getUserObject();
            ex.setNum_paso(this.jcmbxNumPaso.getSelectedIndex()+1);
            ex.setDescripcion(jtxaDescripcion.getText());
            ex.setTipo(true);
            ex.notificar_observer();
        }
        this.Padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
        this.Padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.Padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrExcepcion().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JComboBox jcmbxNumPaso;
    private javax.swing.JLabel jlblNumPaso;
    private javax.swing.JTextArea jtxaDescripcion;
    // End of variables declaration//GEN-END:variables
}
