/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrPaso.java
 *
 * Created on 26-nov-2011, 20:11:14
 */

package interfaz;

import clases.Caso_de_uso;
import clases.Evento;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Cervantes
 */
public class jfrPaso extends javax.swing.JFrame {

    private Interfaz Padre;
    private DefaultMutableTreeNode nodo_insertar;
    private Caso_de_uso CU;
    private boolean editar;
    /** Creates new form jfrPaso */
    public jfrPaso(Interfaz auxpadre,DefaultMutableTreeNode auxnodo_insertar,Caso_de_uso auxCU,boolean n_editar)
    {
        initComponents();
        this.Padre=auxpadre;
        this.nodo_insertar=auxnodo_insertar;
        this.CU=auxCU;
        this.editar=n_editar;
        if(n_editar)this.inicializar_edicion();
    }

    private void inicializar_edicion()
    {
        Evento paso=(Evento) this.nodo_insertar.getUserObject();
        this.jtxaDescripcion.setText(paso.getDescripcion());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir paso...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtxaDescripcion.setColumns(20);
        jtxaDescripcion.setLineWrap(true);
        jtxaDescripcion.setRows(5);
        jtxaDescripcion.setName("jtxaDescripcion"); // NOI18N
        jScrollPane1.setViewportView(jtxaDescripcion);

        jLabel1.setText("Descripción:");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText("Aceptar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setName("jbtnCancelar"); // NOI18N
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancelar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancelar)
                        .addGap(19, 19, 19))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jbtnCancelar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jbtnCancelar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //añadir paso al caso de uso
        if(!this.editar)
        {
            Evento nuevo_paso=new Evento();
            nuevo_paso.setDescripcion(this.jtxaDescripcion.getText());
            nuevo_paso.setNum_paso(this.nodo_insertar.getChildCount()+1);
            nuevo_paso.setTipo(false);
            nuevo_paso.addObserver(this.Padre);
            nuevo_paso.setPertenece(CU);
            this.CU.nuevo_Paso(nuevo_paso);
            this.nodo_insertar.add(new DefaultMutableTreeNode(nuevo_paso));
            nuevo_paso.notificar_observer();
        }
        else
        {
            Evento paso=(Evento) this.nodo_insertar.getUserObject();
            paso.setDescripcion(this.jtxaDescripcion.getText());
            paso.setNum_paso(this.nodo_insertar.getChildCount()+1);
            paso.setTipo(false);
            paso.addObserver(this.Padre);
            paso.notificar_observer();
        }
        this.Padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
        this.Padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.Padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrPaso().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JTextArea jtxaDescripcion;
    // End of variables declaration//GEN-END:variables

}
