/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrUseCaseDialog.java
 *
 * Created on 05-nov-2011, 19:00:01
 */

package interfaz;

import clases.Caso_de_uso;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Cervantes
 */
public class jfrUseCaseDialog extends javax.swing.JFrame {
    Interfaz padre;
    DefaultMutableTreeNode nodo_insercion;
    private boolean editar;
    /** Creates new form jfrUseCaseDialog */
    public jfrUseCaseDialog(Interfaz padre, DefaultMutableTreeNode nodo,boolean n_editar) {
        initComponents();
        this.padre = padre;
        this.nodo_insercion = nodo;
        this.editar=n_editar;
        if(n_editar) this.inicializar_edicion();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtAceptar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxNombreCU = new javax.swing.JTextField();
        jchkAbstracto = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxaEvento = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jtxFrecuencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcmbTiempo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxaDetalle = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaPrecondicion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxaPostcondicion = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbPriInicio = new javax.swing.JComboBox();
        jcbPriElaboracion = new javax.swing.JComboBox();
        jcbPriConstruccion = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxaComentarios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Caso de Uso");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jbtAceptar.setText("Aceptar");
        jbtAceptar.setEnabled(false);
        jbtAceptar.setName("jbtAceptar"); // NOI18N
        jbtAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAceptarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.setName("jbtCancelar"); // NOI18N
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText("Nombre del CU:");
        jLabel3.setName("jLabel3"); // NOI18N

        jtxNombreCU.setName("jtxNombreCU"); // NOI18N
        jtxNombreCU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxNombreCUKeyReleased(evt);
            }
        });

        jchkAbstracto.setText("Es abstracto");
        jchkAbstracto.setName("jchkAbstracto"); // NOI18N

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento de activación"));
        jPanel11.setName("jPanel11"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jtxaEvento.setColumns(20);
        jtxaEvento.setLineWrap(true);
        jtxaEvento.setRows(5);
        jtxaEvento.setName("jtxaEvento"); // NOI18N
        jScrollPane5.setViewportView(jtxaEvento);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        jLabel4.setText("Frecuencia:");
        jLabel4.setName("jLabel4"); // NOI18N

        jtxFrecuencia.setName("jtxFrecuencia"); // NOI18N

        jLabel5.setText("veces cada");
        jLabel5.setName("jLabel5"); // NOI18N

        jcmbTiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "día", "semana", "año" }));
        jcmbTiempo.setName("jcmbTiempo"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxNombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jchkAbstracto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxNombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jchkAbstracto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcmbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("El sistema deberá"));
        jPanel10.setName("jPanel10"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jtxaDetalle.setColumns(20);
        jtxaDetalle.setLineWrap(true);
        jtxaDetalle.setRows(5);
        jtxaDetalle.setName("jtxaDetalle"); // NOI18N
        jScrollPane3.setViewportView(jtxaDetalle);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Detalle", jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setName("jPanel8"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtxaPrecondicion.setColumns(20);
        jtxaPrecondicion.setLineWrap(true);
        jtxaPrecondicion.setRows(5);
        jtxaPrecondicion.setName("jtxaPrecondicion"); // NOI18N
        jScrollPane1.setViewportView(jtxaPrecondicion);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        jLabel1.setText("Precondición:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Postcondición:");
        jLabel2.setName("jLabel2"); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(166, 96));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jtxaPostcondicion.setColumns(20);
        jtxaPostcondicion.setLineWrap(true);
        jtxaPostcondicion.setRows(5);
        jtxaPostcondicion.setName("jtxaPostcondicion"); // NOI18N
        jScrollPane2.setViewportView(jtxaPostcondicion);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pre/Post", jPanel3);

        jPanel4.setName("jPanel4"); // NOI18N

        jLabel6.setText("Durante la fase de inicio:");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Durante la fase de elaboración:");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("Durante la fase de construcción:");
        jLabel8.setName("jLabel8"); // NOI18N

        jcbPriInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Puede esperar", "Es importante pero no inmediato", "Es muy importante", "Urgente" }));
        jcbPriInicio.setName("jcbPriInicio"); // NOI18N

        jcbPriElaboracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Puede esperar", "Es importante pero no inmediato", "Es muy importante", "Urgente" }));
        jcbPriElaboracion.setName("jcbPriElaboracion"); // NOI18N

        jcbPriConstruccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Puede esperar", "Es importante pero no inmediato", "Es muy importante", "Urgente" }));
        jcbPriConstruccion.setName("jcbPriConstruccion"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbPriConstruccion, 0, 0, Short.MAX_VALUE)
                    .addComponent(jcbPriElaboracion, 0, 0, Short.MAX_VALUE)
                    .addComponent(jcbPriInicio, 0, 178, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbPriInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbPriElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jcbPriConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prioridad", jPanel4);

        jPanel5.setName("jPanel5"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Rastreabilidad", jPanel5);

        jPanel7.setName("jPanel7"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jtxaComentarios.setColumns(20);
        jtxaComentarios.setLineWrap(true);
        jtxaComentarios.setRows(5);
        jtxaComentarios.setName("jtxaComentarios"); // NOI18N
        jScrollPane4.setViewportView(jtxaComentarios);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Comentarios", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancelar)
                    .addComponent(jbtAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializar_edicion()
    {
        Caso_de_uso CU=(Caso_de_uso)this.nodo_insercion.getUserObject();
        this.jtxNombreCU.setText(CU.getNombre());
        this.jchkAbstracto.setSelected(CU.getAbstracto());
        this.jtxaEvento.setText(CU.getEvento());
        this.jtxFrecuencia.setText(CU.getFrecuencia());
        this.jcmbTiempo.setSelectedItem(CU.getUnidad());
        this.jtxaDetalle.setText(CU.getDetalle());
        this.jtxaPrecondicion.setText(CU.getPrecondicion());
        this.jtxaPostcondicion.setText(CU.getPostcondicion());
        this.jcbPriConstruccion.setSelectedItem(CU.getPriInicio());
        this.jcbPriElaboracion.setSelectedItem(CU.getPriElaboracion());
        this.jcbPriConstruccion.setSelectedItem(CU.getPriConstruccion());
        this.jtxaComentarios.setText(CU.getComentario());
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.padre.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        // TODO add your handling code here:
        padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAceptarActionPerformed
        // TODO add your handling code here:
        //Al pulsar aceptar debemos insertar la informacion obtenida en el arbol de la clase interfaz.
        if(!this.editar)
        {
            Caso_de_uso CU=new Caso_de_uso();
            CU.setNombre(jtxNombreCU.getText());
            CU.setFrecuencia(jtxFrecuencia.getText());
            CU.setUnidad(jcmbTiempo.getSelectedItem().toString());
            CU.setDetalle(jtxaDetalle.getText());
            CU.setAbstracto(this.jchkAbstracto.isSelected());
            CU.setEvento(jtxaEvento.getText());
            CU.setPrecondicion(jtxaPrecondicion.getText());
            CU.setPostcondicion(jtxaPostcondicion.getText());
            CU.setComentario(jtxaComentarios.getText());
            CU.setPriInicio(jcbPriInicio.getSelectedItem().toString());
            CU.setPriElaboracion(jcbPriElaboracion.getSelectedItem().toString());
            CU.setPriConstruccion(jcbPriConstruccion.getSelectedItem().toString());

            CU.addObserver(this.padre);
            this.padre.getDoc().Crear_CU(CU);
            DefaultMutableTreeNode nodo=new DefaultMutableTreeNode(CU);
            nodo.add(new DefaultMutableTreeNode("Pasos"));
            nodo.add(new DefaultMutableTreeNode("Excepciones"));
            this.nodo_insercion.add(nodo);
            this.padre.añadir_cosa(nodo);
            CU.notificar_observer();
        }
        else
        {
            Caso_de_uso CU=(Caso_de_uso)this.nodo_insercion.getUserObject();
            CU.setNombre(jtxNombreCU.getText());
            CU.setFrecuencia(jtxFrecuencia.getText());
            CU.setUnidad(jcmbTiempo.getSelectedItem().toString());
            CU.setDetalle(jtxaDetalle.getText());
            CU.setAbstracto(this.jchkAbstracto.isSelected());
            CU.setEvento(jtxaEvento.getText());
            CU.setPrecondicion(jtxaPrecondicion.getText());
            CU.setPostcondicion(jtxaPostcondicion.getText());
            CU.setComentario(jtxaComentarios.getText());
            CU.setPriInicio(jcbPriInicio.getSelectedItem().toString());
            CU.setPriElaboracion(jcbPriElaboracion.getSelectedItem().toString());
            CU.setPriConstruccion(jcbPriConstruccion.getSelectedItem().toString());
            CU.notificar_observer();
        }
        this.padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jbtAceptarActionPerformed

    private void jtxNombreCUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNombreCUKeyReleased
        // TODO add your handling code here:
        if(!jtxNombreCU.getText().equals(""))
        {
            jbtAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_jtxNombreCUKeyReleased

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtAceptar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JComboBox jcbPriConstruccion;
    private javax.swing.JComboBox jcbPriElaboracion;
    private javax.swing.JComboBox jcbPriInicio;
    private javax.swing.JCheckBox jchkAbstracto;
    private javax.swing.JComboBox jcmbTiempo;
    private javax.swing.JTextField jtxFrecuencia;
    private javax.swing.JTextField jtxNombreCU;
    private javax.swing.JTextArea jtxaComentarios;
    private javax.swing.JTextArea jtxaDetalle;
    private javax.swing.JTextArea jtxaEvento;
    private javax.swing.JTextArea jtxaPostcondicion;
    private javax.swing.JTextArea jtxaPrecondicion;
    // End of variables declaration//GEN-END:variables

}
