/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrmGlosario.java
 *
 * Created on 16-ene-2012, 23:22:23
 */
package interfaz;

import clases.Apendice;
import clases.Glosario;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author amaranto
 */
public class jfrGlosario extends javax.swing.JFrame {

    /** Creates new form jfrmGlosario */
    Interfaz padre;
    DefaultMutableTreeNode nodo;
    private boolean editar;
    
    public jfrGlosario(Interfaz padre, DefaultMutableTreeNode nodo,boolean n_editar) {
        initComponents();
        this.padre = padre;
        this.nodo = nodo;
        this.editar=n_editar;
        if(n_editar)this.inicializar_edicion();
    }

    
    private void inicializar_edicion()
    {
        Glosario g=(Glosario)this.nodo.getUserObject();
        this.jTxtermino.setText(g.getPalabra());
        this.jTxtsignificado.setText(g.getDescripcion());
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtermino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtsignificado = new javax.swing.JTextArea();
        jBtaceptar = new javax.swing.JButton();
        jBtcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir termino de glosario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Término del glosario: ");

        jTxtermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxterminoActionPerformed(evt);
            }
        });

        jLabel2.setText("Significado: ");

        jTxtsignificado.setColumns(20);
        jTxtsignificado.setRows(5);
        jScrollPane1.setViewportView(jTxtsignificado);

        jBtaceptar.setText("Aceptar");
        jBtaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtaceptarActionPerformed(evt);
            }
        });

        jBtcancelar.setText("Cancelar");
        jBtcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtaceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtcancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtermino, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtcancelar)
                    .addComponent(jBtaceptar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(padre != null)
        {
            padre.setEnabled(true);
        }
        
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jBtcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtcancelarActionPerformed
        // TODO add your handling code here:
        if(padre != null)
        {
            padre.setEnabled(true);
        }
        
        this.dispose();
    }//GEN-LAST:event_jBtcancelarActionPerformed

private void jTxterminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxterminoActionPerformed
// TODO add your handling code here:
    


}//GEN-LAST:event_jTxterminoActionPerformed

private void jBtaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtaceptarActionPerformed
// TODO add your handling code here:
   //Esto nos permite Conocer el antecesor del glosario y guardarlo en el sitio donde debe de ir   
    if(!this.editar)
    {
        Glosario n_glosario = new Glosario();
        if(nodo.getUserObject() instanceof Apendice){
            Apendice Apend = (Apendice)nodo.getUserObject();
            n_glosario.setAntecesor(Apend);
            if(Apend.isTipo()){
            System.out.println("Antecesor Apendice : "+Apend.getNombre());
            }else{
            System.out.println("Antecesor Sección : "+Apend.getNombre());
            }
        }

        n_glosario.setPalabra(jTxtermino.getText());
        n_glosario.setDescripcion(jTxtsignificado.getText());
        n_glosario.addObserver(this.padre);
        this.padre.getDoc().Añadir_Glosario(n_glosario);
        DefaultMutableTreeNode nodo_nuevo=new DefaultMutableTreeNode(n_glosario);
        this.nodo.add(nodo_nuevo);
        this.padre.añadir_cosa(nodo_nuevo);
        n_glosario.notificar_observer();
    }
    else
    {
        Glosario n_glosario=(Glosario) this.nodo.getUserObject();
        n_glosario.setPalabra(jTxtermino.getText());
        n_glosario.setDescripcion(jTxtsignificado.getText());
        n_glosario.notificar_observer();
    }
    this.padre.setEnabled(true);
    this.dispose();
    
}//GEN-LAST:event_jBtaceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new jfrGlosario(null, null,false).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtaceptar;
    private javax.swing.JButton jBtcancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtermino;
    private javax.swing.JTextArea jTxtsignificado;
    // End of variables declaration//GEN-END:variables
}
