/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrReqFuncionalidad.java
 *
 * Created on Dec 18, 2011, 1:44:35 PM
 */

package interfaz;

import clases.RInformacion;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author jackpanzer
 */
public class jfrReqInformacion extends javax.swing.JFrame {

    /** Creates new form jfrReqFuncionalidad */
    Interfaz padre;
    DefaultListModel model;
    DefaultMutableTreeNode nodo_insercion;
    private boolean editar;
    
    public jfrReqInformacion(Interfaz padre,DefaultMutableTreeNode nodo,boolean n_editar) {
        initComponents();
        this.padre = padre;
        jbtnAceptar.setEnabled(false);
        model = new DefaultListModel();
        jlstDependencia.setModel(model);
        this.nodo_insercion=nodo;
        this.editar=n_editar;
        if(n_editar)this.inicializar_edicion();
    }

    
    private void inicializar_edicion()
    {
        RInformacion ri=(RInformacion) this.nodo_insercion.getUserObject();
        this.jtxNombre.setText(ri.getNombre());
        if(ri.isTipo())
        {
            this.jcbInfo.setSelected(true);
            this.jcbArquitectura.setSelected(false);
        }
        else
        {
            this.jcbInfo.setSelected(false);
            this.jcbArquitectura.setSelected(true);
        }
        this.jtxVersion.setText(ri.getVersion());
        this.jtxaDescripcion.setText(ri.getDescripcion());
        for(String aux:ri.getDependencia())
            this.model.addElement(aux);
        this.jtxTiempoVidaU.setText(ri.getTv_unidad());
        this.jtxTiempoOcupadoC.setText(ri.getTv_cantidad());
        this.jtxTiempoOcupadoU.setText(ri.getTocu_unidad());
        this.jtxTiempoOcupadoC.setText(ri.getTocu_cantidad());
        this.jcmbImportancia.setSelectedItem(ri.getImportancia());
        this.jcmbEstado.setSelectedItem(ri.getEstado());
        this.jcmbEstabilidad.setSelectedItem(ri.getEstabilidad());
        this.jcmbUrgencia.setSelectedItem(ri.getUrgencia());
        this.jtxaComentarios.setText(ri.getComentario());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jcbInfo = new javax.swing.JCheckBox();
        jcbArquitectura = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jtxVersion = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDescripcion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlstDependencia = new javax.swing.JList();
        jtxDepTemporal = new javax.swing.JTextField();
        jbtnAgregar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxTiempoVidaC = new javax.swing.JTextField();
        jtxTiempoVidaU = new javax.swing.JTextField();
        jtxTiempoOcupadoC = new javax.swing.JTextField();
        jtxTiempoOcupadoU = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcmbImportancia = new javax.swing.JComboBox();
        jcmbUrgencia = new javax.swing.JComboBox();
        jcmbEstado = new javax.swing.JComboBox();
        jcmbEstabilidad = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxaComentarios = new javax.swing.JTextArea();
        jbtnCancelar = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir requisito de informacion");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel5.setText("Nombre:");
        jLabel5.setName("jLabel5"); // NOI18N

        jtxNombre.setName("jtxNombre"); // NOI18N
        jtxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxNombreKeyReleased(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de requisito"));
        jPanel5.setName("jPanel5"); // NOI18N

        jcbInfo.setText("Relacionada con información");
        jcbInfo.setName("jcbInfo"); // NOI18N
        jcbInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInfoActionPerformed(evt);
            }
        });

        jcbArquitectura.setText("Relacionada con arquitectura");
        jcbArquitectura.setName("jcbArquitectura"); // NOI18N
        jcbArquitectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbArquitecturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbInfo)
                    .addComponent(jcbArquitectura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jcbInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbArquitectura)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel6.setText("Versión:");
        jLabel6.setName("jLabel6"); // NOI18N

        jtxVersion.setName("jtxVersion"); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jPanel6.setName("jPanel6"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtxaDescripcion.setColumns(20);
        jtxaDescripcion.setLineWrap(true);
        jtxaDescripcion.setRows(5);
        jtxaDescripcion.setName("jtxaDescripcion"); // NOI18N
        jScrollPane1.setViewportView(jtxaDescripcion);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jlstDependencia.setName("jlstDependencia"); // NOI18N
        jScrollPane3.setViewportView(jlstDependencia);

        jtxDepTemporal.setName("jtxDepTemporal"); // NOI18N
        jtxDepTemporal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxDepTemporalKeyReleased(evt);
            }
        });

        jbtnAgregar.setText("Añadir");
        jbtnAgregar.setName("jbtnAgregar"); // NOI18N
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.setName("jbtnEliminar"); // NOI18N
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jLabel7.setText("Tiempo de vida:");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("cada");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("Tiempo ocupado:");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("cada");
        jLabel10.setName("jLabel10"); // NOI18N

        jtxTiempoVidaC.setName("jtxTiempoVidaC"); // NOI18N

        jtxTiempoVidaU.setName("jtxTiempoVidaU"); // NOI18N

        jtxTiempoOcupadoC.setName("jtxTiempoOcupadoC"); // NOI18N

        jtxTiempoOcupadoU.setName("jtxTiempoOcupadoU"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxTiempoVidaC)
                            .addComponent(jtxTiempoOcupadoC, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxTiempoOcupadoU))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxTiempoVidaU, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxDepTemporal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEliminar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxDepTemporal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEliminar)
                    .addComponent(jbtnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jtxTiempoVidaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxTiempoVidaU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jtxTiempoOcupadoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxTiempoOcupadoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dependencia", jPanel2);

        jPanel4.setName("jPanel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Rastreabilidad", jPanel4);

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel1.setText("Importancia:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Urgencia:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Estado:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Estabilidad:");
        jLabel4.setName("jLabel4"); // NOI18N

        jcmbImportancia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nada importante", "Algo importante", "Muy importante" }));
        jcmbImportancia.setName("jcmbImportancia"); // NOI18N

        jcmbUrgencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No es urgente", "Es algo urgente", "Es bastante urgente", "Urgencia inmediata" }));
        jcmbUrgencia.setName("jcmbUrgencia"); // NOI18N

        jcmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Planificando", "En desarrollo", "Depurando", "Completo" }));
        jcmbEstado.setName("jcmbEstado"); // NOI18N

        jcmbEstabilidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muy estable", "Bastante estable", "No muy estable", "No estable" }));
        jcmbEstabilidad.setName("jcmbEstabilidad"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jcmbEstabilidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcmbImportancia, 0, 182, Short.MAX_VALUE)
                            .addComponent(jcmbUrgencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(126, 126, 126))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbImportancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbEstabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prioridades", jPanel3);

        jPanel7.setName("jPanel7"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jtxaComentarios.setColumns(20);
        jtxaComentarios.setLineWrap(true);
        jtxaComentarios.setRows(5);
        jtxaComentarios.setName("jtxaComentarios"); // NOI18N
        jScrollPane2.setViewportView(jtxaComentarios);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Comentarios", jPanel7);

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setName("jbtnCancelar"); // NOI18N
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.setName("jbtnAceptar"); // NOI18N
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar)
                    .addComponent(jbtnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInfoActionPerformed
        // TODO add your handling code here:
        jcbInfo.setSelected(true);
        jcbArquitectura.setSelected(false);

        if((jtxNombre.getText().equals("")) || (!jcbInfo.isSelected() &&
                !jcbArquitectura.isSelected()))
        {
            jbtnAceptar.setEnabled(false);
        }
        else
            jbtnAceptar.setEnabled(true);
}//GEN-LAST:event_jcbInfoActionPerformed

    private void jcbArquitecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbArquitecturaActionPerformed
        // TODO add your handling code here:
        jcbInfo.setSelected(false);
        jcbArquitectura.setSelected(true);

        if((jtxNombre.getText().equals("")) || (!jcbInfo.isSelected() &&
                !jcbArquitectura.isSelected()))
        {
            jbtnAceptar.setEnabled(false);
        }
        else
            jbtnAceptar.setEnabled(true);
}//GEN-LAST:event_jcbArquitecturaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(padre != null)
            padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
        if(padre != null)
            padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jtxNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNombreKeyReleased
        // TODO add your handling code here:
        if((jtxNombre.getText().equals("")) || (!jcbInfo.isSelected() &&
                !jcbArquitectura.isSelected()))
        {
            jbtnAceptar.setEnabled(false);
        }
        else
            jbtnAceptar.setEnabled(true);
    }//GEN-LAST:event_jtxNombreKeyReleased

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        // TODO add your handling code here:
        if(jtxDepTemporal.getText().equals(""))
        {
        }
        else
        {
            model.addElement(jtxDepTemporal.getText());
            jlstDependencia.setSelectedIndex(-1);
            jtxDepTemporal.setText("");
        }
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        if(jlstDependencia.getSelectedIndex() != -1)
        {
            //System.out.println((String)model.getElementAt(jlstDependencia.getSelectedIndex()));
            model.remove(jlstDependencia.getSelectedIndex());
            jlstDependencia.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jtxDepTemporalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxDepTemporalKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if(jtxDepTemporal.getText().equals(""))
            {
            }
            else
            {
                model.addElement(jtxDepTemporal.getText());
                jlstDependencia.setSelectedIndex(-1);
                jtxDepTemporal.setText("");
            }
        }
    }//GEN-LAST:event_jtxDepTemporalKeyReleased

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        // TODO add your handling code here:
        if(!this.editar)
        {
            ArrayList<String> dep = new ArrayList<String>();
            for(int i = 0; i < model.capacity(); i++)
            {
                try
                {
                    if(!dep.contains((String)model.get(i)))
                        dep.add((String)model.get(i));
                    System.out.println((String)model.get(i));
                }
                catch(ArrayIndexOutOfBoundsException ex)
                {
                }
            }
            DefaultMutableTreeNode nodo=null;
            RInformacion ri=new RInformacion();
            ri.setNombre(this.jtxNombre.getText());
            if(this.jcbInfo.isSelected())
                ri.setTipo(true);
            else if(this.jcbArquitectura.isSelected())
                ri.setTipo(false);
            ri.setVersion(this.jtxVersion.getText());
            ri.setDescripcion(this.jtxaDescripcion.getText());
            ri.setDependencia(dep);
            ri.setImportancia((String)this.jcmbImportancia.getSelectedItem());
            ri.setUrgencia((String)this.jcmbUrgencia.getSelectedItem());
            ri.setEstado((String)this.jcmbEstado.getSelectedItem());
            ri.setEstabilidad((String)this.jcmbEstabilidad.getSelectedItem());
            ri.setComentario(this.jtxaComentarios.getText());
            ri.setTv_cantidad(this.jtxTiempoVidaC.getText());
            ri.setTv_unidad(this.jtxTiempoVidaU.getText());
            ri.setTocu_cantidad(this.jtxTiempoOcupadoC.getText());
            ri.setTocu_unidad(this.jtxTiempoOcupadoU.getText());
            ri.addObserver(this.padre);
            this.padre.getDoc().Crear_Req(ri);
            nodo=new DefaultMutableTreeNode(ri);
            this.nodo_insercion.add(nodo);
            this.padre.añadir_cosa(nodo);
            ri.notificar_observer();
        }
        else
        {
            RInformacion ri=(RInformacion) this.nodo_insercion.getUserObject();
            ArrayList<String> dep = new ArrayList<String>();
            for(int i = 0; i < model.capacity(); i++)
            {
                try
                {
                    if(!dep.contains((String)model.get(i)))
                        dep.add((String)model.get(i));
                    System.out.println((String)model.get(i));
                }
                catch(ArrayIndexOutOfBoundsException ex)
                {
                }
                ri.setNombre(this.jtxNombre.getText());
            if(this.jcbInfo.isSelected())
                ri.setTipo(true);
            else if(this.jcbArquitectura.isSelected())
                ri.setTipo(false);
            ri.setVersion(this.jtxVersion.getText());
            ri.setDescripcion(this.jtxaDescripcion.getText());
            ri.setDependencia(dep);
            ri.setImportancia((String)this.jcmbImportancia.getSelectedItem());
            ri.setUrgencia((String)this.jcmbUrgencia.getSelectedItem());
            ri.setEstado((String)this.jcmbEstado.getSelectedItem());
            ri.setEstabilidad((String)this.jcmbEstabilidad.getSelectedItem());
            ri.setComentario(this.jtxaComentarios.getText());
            ri.setTv_cantidad(this.jtxTiempoVidaC.getText());
            ri.setTv_unidad(this.jtxTiempoVidaU.getText());
            ri.setTocu_cantidad(this.jtxTiempoOcupadoC.getText());
            ri.setTocu_unidad(this.jtxTiempoOcupadoU.getText());
            ri.notificar_observer();
            }
            
        }
        this.padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrReqInformacion(null).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JCheckBox jcbArquitectura;
    private javax.swing.JCheckBox jcbInfo;
    private javax.swing.JComboBox jcmbEstabilidad;
    private javax.swing.JComboBox jcmbEstado;
    private javax.swing.JComboBox jcmbImportancia;
    private javax.swing.JComboBox jcmbUrgencia;
    private javax.swing.JList jlstDependencia;
    private javax.swing.JTextField jtxDepTemporal;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextField jtxTiempoOcupadoC;
    private javax.swing.JTextField jtxTiempoOcupadoU;
    private javax.swing.JTextField jtxTiempoVidaC;
    private javax.swing.JTextField jtxTiempoVidaU;
    private javax.swing.JTextField jtxVersion;
    private javax.swing.JTextArea jtxaComentarios;
    private javax.swing.JTextArea jtxaDescripcion;
    // End of variables declaration//GEN-END:variables

}
